
# Site settings

url: "https://chuguet.github.io"
baseurl: ""
google-tracking-id: "UA-79651282-1"
force-https: True

syntax-highlight: True

# Sections shown in the index page

pages_list:
  About: 'about'
  #Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

web-app-mode: True

# Icons for Chrome Web App mode https://developer.chrome.com/multidevice/android/installtohomescreen
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

#############
# HTML Head #
#############

author: "Carlos Huguet"
lang: "en"
title: "{ chuguet }"
favicon: "/img/favicon.ico"
description: "Blog of Carlos Huguet, blogging mainly about tech. Build your own way."
keywords: "carlos, huguet, chuguet, huguet10, technology, computer science, java, javascript, backbone, marionette, front, tdd"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/back.jpg"
me-img: "../img/default.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: Flase # Shuffle the lines.
loop: False
loop-count: 1 # Set False for infinite loop, or set any number for finite loop.
type-speed: 4 # Default 10
start-delay: 2000 # Default 200
delete-delay: 50000 # Default 5000
lines: # You can add HTML Tags in the Text
  - text: "Welcome to the real world ..."

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "chuguet"

###############
# Life Events #
###############

events:
  - image: "/img/career/ing.png"
    date: "June 2014 - Currently"
    description: "Analyst Programmer worked <a href=\"http://www.ingdirect.es\" target=\"_blank\">@ ING Bank</a> at ING Direct"
  - image: "/img/career/upm.png"
    date: "Sept 2014 - June 2015"
    description: "Master Web Engineering <a href=\"http://www.upm.es\" target=\"_blank\">@ UPM</a>"
  - image: "/img/career/upsam.png"
    date: "Sept 2012 - May 2014"
    description: "IT Enginer <a href=\"http://www.upsam.com\" target=\"_blank\">@ UPSAM</a>"
  - image: "/img/career/factoria_etsia.png"
    date: "January 2012 - May 2014"
    description: "Senior Programmer worked <a href=\"http://www.betcompara.com/inicio\" target=\"_blank\">@ Betcompara</a> at <br/><a href=\"http://www.factoriaetsia.com/\" target=\"_blank\">@ Factoria ETSIA</a>"
  - image: "/img/career/coritel.png"
    date: "Aug 2011 - December 2011"
    description: "Junior Programmer worked <a href=\"https://coritel.es\" target=\"_blank\">@ Coritel</a> over J2EE for a client of financial sector (ISBAN)"
  - image: "/img/career/uma.png"
    date: "Sept 2007 - June 2011"
    description: "IT Technical Engineer <a href=\"http://www.uma.es\" target=\"_blank\">@ UMA</a>"

# First image of the Career timeline
timeline-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "huguet10@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/chuguet"
  - title: "linkedin"
    url: "https://es.linkedin.com/in/chuguet"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables bellow this point!

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

gems:
  - jekyll-paginate
  - jemoji
